[[redirects]]
from = "/toppings"
to = "https://my-json-server.typicode.com/Bombloperta/pizza-al-salame/src/data/db.json/toppings"
status = 200

[[redirects]]
from = "/pizzas"
to = "https://my-json-server.typicode.com/Bombloperta/pizza-al-salame/src/data/db.json/pizzas"
status = 200

[[redirects]]
from = "/photos"
to = "https://my-json-server.typicode.com/Bombloperta/pizza-al-salame/src/data/db.json/photos"
status = 200
